# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ray55\PycharmProjects\TaskProcessorUI\UI\qt\window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1567, 1191)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main = QtWidgets.QHBoxLayout()
        self.main.setObjectName("main")
        self.fileManager = QtWidgets.QVBoxLayout()
        self.fileManager.setObjectName("fileManager")
        self.searchBar = QtWidgets.QHBoxLayout()
        self.searchBar.setObjectName("searchBar")
        self.searchEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.searchEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.searchEdit.setInputMask("")
        self.searchEdit.setText("")
        self.searchEdit.setObjectName("searchEdit")
        self.searchBar.addWidget(self.searchEdit)
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setObjectName("searchButton")
        self.searchBar.addWidget(self.searchButton)
        self.searchBar.setStretch(0, 3)
        self.searchBar.setStretch(1, 1)
        self.fileManager.addLayout(self.searchBar)
        self.fileViewer = QtWidgets.QTreeView(self.centralwidget)
        self.fileViewer.setObjectName("fileViewer")
        self.fileManager.addWidget(self.fileViewer)
        self.fileManager.setStretch(1, 5)
        self.main.addLayout(self.fileManager)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.widget.setObjectName("widget")
        self.main.addWidget(self.widget)
        self.main.setStretch(0, 2)
        self.main.setStretch(1, 5)
        self.horizontalLayout.addLayout(self.main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1567, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.searchEdit.setToolTip(_translate("MainWindow", "Insert a file path."))
        self.searchButton.setToolTip(_translate("MainWindow", "Search for a file path."))
        self.searchButton.setText(_translate("MainWindow", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
